services:
  nginx-1:
    image: nginx
    restart: always
    ports:
      - 8086:80
    depends_on:
      - php-1
    volumes:
      - ./app1/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app1:/var/www/html/app1

  nginx-2:
    image: nginx
    restart: always
    ports:
      - 8087:80
    depends_on:
      - php-2
    volumes:
      - ./app2/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app2:/var/www/html/app2

  php-1:
    restart: always
    build:
      context: ./app1
      dockerfile: Dockerfile
    volumes:
      - ./app1:/var/www/html/app1    
    ports:
      - 5086:9000
    depends_on:
      - mysql

  php-2:
    restart: always
    build:
      context: ./app2
      dockerfile: Dockerfile
    volumes:
      - ./app2:/var/www/html/app2
    ports:
      - 5087:9000
    depends_on:
      - mysql
         
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: laravel
      MYSQL_DATABASE: example_app
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: